module.exports={
   MONGO_URI:process.env.MONGO_URI,
   SECRET_KEY:process.env.SECRET_KEY,
    JWT_ACC_ACTIVATE:process.env.JWT_ACC_ACTIVATE,
    JWT_ACCOUNT_ACTIVATION:process.env.JWT_ACCOUNT_ACTIVATION,
    JWT_RESET_PASSWORD:process.env.JWT_RESET_PASSWORD,
    CLIENT_URL:process.env.CLIENT_URL,
    EMAIL:process.env.EMAIL,
    PASS:process.env.PASS,
}
